In [76]:
%matplotlib inline 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [77]:
df = pd.read_csv('malta_properties.csv',index_col =[0])
df

          LOCATION     PRICE TYPE_OF_PROPERTY POOL GARAGE  DATE  BEDROOM  SQM
0           BALZAN  152000.0        apartment   No     No  2015        3  NaN
1             GOZO  185000.0            house   No     No  2015        3  NaN
2             GOZO  293000.0            house  Yes     No  2015        3  NaN
3             GOZO  145000.0       maisonette   No     No  2015        3  NaN
4       MARSASCALA   85000.0        apartment   No     No  2015        2  NaN
...            ...       ...              ...  ...    ...   ...      ...  ...
103848      SWIEQI  375000.0       maisonette   No    Yes  2022        3  NaN
103849     TARXIEN  310000.0       maisonette   No     No  2022        3  NaN
103850    VALLETTA  575000.0            house   No     No  2022        3  NaN
103851      ŻEBBUĠ  245000.0        apartment   No     No  2022        3  NaN
103852      ŻEJTUN  250000.0       maisonette  Yes     No  2022        3  NaN

[103853 rows x 8 columns]

In [87]:
a = df['LOCATION'].value_counts().head(10).index.tolist()
a

['SLIEMA',
 'GOZO',
 'MOSTA',
 'MARSASCALA',
 'ST JULIANS',
 'ST PAUL',
 'QAWRA',
 'BIRKIRKARA',
 'ATTARD',
 'MELLIEĦA']

In [88]:
new_df = df[(df['TYPE_OF_PROPERTY'] == 'house') & (df['DATE'] == 2022) & (df['POOL'] == 'No') & (df['LOCATION'].isin(a))]
new_df

          LOCATION     PRICE TYPE_OF_PROPERTY POOL GARAGE  DATE  BEDROOM  SQM
97758   BIRKIRKARA  395000.0            house   No     No  2022        3  NaN
97760   BIRKIRKARA  290000.0            house   No     No  2022        3  NaN
97762   BIRKIRKARA  315700.0            house   No     No  2022        3  NaN
97763   BIRKIRKARA  290000.0            house   No     No  2022        3  NaN
97764   BIRKIRKARA  320000.0            house   No     No  2022        3  NaN
...            ...       ...              ...  ...    ...   ...      ...  ...
103830      SLIEMA  375000.0            house   No     No  2022        3  NaN
103831      SLIEMA  350000.0            house   No     No  2022        2  NaN
103833      SLIEMA  430000.0            house   No     No  2022        3  NaN
103834      SLIEMA  298000.0            house   No     No  2022        3  NaN
103842     ST PAUL  213000.0            house   No     No  2022        2  NaN

[598 rows x 8 columns]

In [89]:
new_df_rows_2022 = np.random.choice(new_df.index.values, 30)
new_df_rows_2022

array([100484, 101874, 101247, 100068, 100888, 101608,  99012,  97932,
       100041, 102720,  99544,  99434, 101938, 101336, 102726, 101200,
        98102, 100484, 100238, 100484,  99549, 102683, 103677, 103058,
       100015,  97951, 103428, 100487,  98541,  99501], dtype=int64)

In [90]:
new_df_2022 = df.loc[new_df_rows_2022]
new_df_2022

,LOCATION,PRICE,TYPE_OF_PROPERTY,POOL,GARAGE,DATE,BEDROOM,SQM
100484,BIRKIRKARA,335000.0,house,No,No,2022,3,170.0
101874,QAWRA,250000.0,house,No,No,2022,2,NaN
101247,SLIEMA,350000.0,house,No,No,2022,2,NaN
100068,MARSASCALA,425000.0,house,No,No,2022,3,125.0
100888,BIRKIRKARA,380000.0,house,No,No,2022,3,NaN
101608,GOZO,235000.0,house,No,No,2022,2,NaN
99012,MOSTA,220000.0,house,No,No,2022,2,NaN
97932,MARSASCALA,465000.0,house,No,No,2022,3,150.0
100041,GOZO,875000.0,house,No,No,2022,4,NaN
102720,MOSTA,565000.0,house,No,No,2022,3,162.0
99544,MARSASCALA,425000.0,house,No,No,2022,3,125.0
99434,SLIEMA,2700000.0,house,No,No,2022,4,NaN
101938,BIRKIRKARA,349000.0,house,No,No,2022,2,NaN
101336,MELLIEĦA,295000.0,house,No,No,2022,3,NaN
102726,MOSTA,490000.0,house,No,Yes,2022,3,NaN
101200,MELLIEĦA,245000.0,house,No,No,2022,3,NaN
98102,MOSTA,650000.0,house,No,No,2022,3,NaN
100484,BIRKIRKARA,335000.0,house,No,No,2022,3,170.0
100238,MOSTA,475000.0,house,No,No,2022,3,128.0
100484,BIRKIRKARA,335000.0,house,No,No,2022,3,170.0
99549,MARSASCALA,275000.0,house,No,No,2022,3,NaN
102683,BIRKIRKARA,349000.0,house,No,No,2022,2,NaN
103677,BIRKIRKARA,285000.0,house,No,No,2022,2,NaN
103058,BIRKIRKARA,300000.0,house,No,No,2022,2,NaN
100015,ATTARD,370000.0,house,No,No,2022,3,NaN
97951,MOSTA,399000.0,house,No,No,2022,3,NaN
103428,BIRKIRKARA,285000.0,house,No,No,2022,3,NaN
100487,BIRKIRKARA,250000.0,house,No,No,2022,3,NaN
98541,ATTARD,190000.0,house,No,No,2022,3,NaN
99501,BIRKIRKARA,645000.0,house,No,No,2022,4,NaN

In [91]:
import scipy.stats as stats
stats.ttest_ind(a=sl_2021['PRICE'],b=sl_2022['PRICE'], equal_var = True)

Ttest_indResult(statistic=-0.6681539736125529, pvalue=0.5066856277568934)

The p-value is greater than 0.05, hence we fail to reject the null hypothesis.

This means that there is no significat difference between the means of the price in Slieme in 2021 and 2022

In [92]:
new_df2 = df[(df['TYPE_OF_PROPERTY'] == 'house') & (df['DATE'] == 2015) & (df['POOL'] == 'No')]
new_df_rows_2015 = np.random.choice(new_df2.index.values, 30)
new_df_2015 = df.loc[new_df_rows_2015]
new_df_2015

         LOCATION     PRICE TYPE_OF_PROPERTY POOL GARAGE  DATE  BEDROOM    SQM
8599     MELLIEĦA  230000.0            house   No    Yes  2015        3    NaN
1745       DINGLI  260000.0            house   No    Yes  2015        3    NaN
17005      ŻEJTUN  272000.0            house   No     No  2015        3    NaN
15728        SAFI  160000.0            house   No     No  2015        2    NaN
4248     SIĠĠIEWI  130000.0            house   No    Yes  2015        2    NaN
17343    SIĠĠIEWI  600000.0            house   No     No  2015        3  854.0
11461       MOSTA  185000.0            house   No     No  2015        3    NaN
8411         GOZO  400000.0            house   No     No  2015        4    NaN
14767      ŻABBAR  128000.0            house   No     No  2015        2    NaN
13364       QORMI  350000.0            house   No    Yes  2015        4  100.0
7634        MSIDA  299000.0            house   No     No  2015        3  350.0
10062      NAXXAR  375000.0            house   No     No  2015        3    NaN
7866       ŻEJTUN   79000.0            house   No     No  2015        3    NaN
13951      NAXXAR  470000.0            house   No    Yes  2015        3    NaN
16200       MOSTA  355000.0            house   No     No  2015        3    NaN
14186      ŻEJTUN  125000.0            house   No     No  2015        3    NaN
11891      GĦAXAQ  135000.0            house   No     No  2015        3  110.0
13899    MELLIEĦA  155000.0            house   No     No  2015        2    NaN
5345        MOSTA  325000.0            house   No    Yes  2015        3    NaN
11043      SLIEMA  179000.0            house   No     No  2015        3    NaN
5558      XGĦAJRA  115750.0            house   No     No  2015        3    NaN
9924     GĦARGĦUR  425000.0            house   No     No  2015        3    NaN
13990       QORMI  100000.0            house   No     No  2015        2    NaN
7983       BALZAN  389000.0            house   No     No  2015        3    NaN
13727  BIRKIRKARA  163000.0            house   No     No  2015        3    NaN
10047       MOSTA  330000.0            house   No    Yes  2015        3    NaN
14014    SENGLEA   480000.0            house   No     No  2015        3  430.0
12024       MOSTA  330000.0            house   No    Yes  2015        3    NaN
10610  ST JULIANS  440000.0            house   No     No  2015        3    NaN
9636       QRENDI  185000.0            house   No     No  2015        3    NaN

Variance is quite similar

In [93]:
var1 = new_df_2015['PRICE'].var()
print(var1)
var2 = new_df_2022['PRICE'].var()
print(var2)

18687479094.827587
201392047126.43674

In [94]:
from scipy.stats import shapiro
print(shapiro(new_df_2015['PRICE']))
print(shapiro(new_df_2022['PRICE']))

ShapiroResult(statistic=0.9408829212188721, pvalue=0.09607899188995361)
ShapiroResult(statistic=0.44921308755874634, pvalue=1.6194952046078015e-09)

Since the value of the p-values is greater than 0.05 it is safe to say that the variable is normally distributed.

All the assumpitons to run a t-test are satisfied.

In [95]:
stats.ttest_ind(a=new_df_2015['PRICE'],b=new_df_2022['PRICE'], equal_var = True)

Ttest_indResult(statistic=-2.170549345455749, pvalue=0.03407211389425838)

The p-value is less than 0.05. The null hypothesis is rejected. Hence there is significant difference between the means of price in 2015 and 2022