In [2]:
import tweepy
import pandas as pd
import json
import snscrape.modules.twitter as sntwitter
import time

We are going to use the twitter api with the library tweepy to get the followers and the following

In [2]:
api_key = "LEqYs6bOKjU7HuNEGiGlU2eSS"
api_secrets = "0WukopJL0Sg7t6QJenUOO0LqojPyTWkSl8oOepDRfui5ybW1Ce"
access_token ="1148685416423395331-Y5rueG3D35JXUVDCNi3y7wHTUL2nMt"
access_secret="ZiVeiScfLKoRxgOAAR3SyJsCeVKli9BPtSxSttjbmkqRQ"

auth = tweepy.OAuthHandler(api_key,api_secrets,access_token, access_secret)

api = tweepy.API(auth)

try:
    api.verify_credentials()
    print('Success')
except:
    print('Fail')

Success

In [3]:
elon= "elonmusk"

Getting the following

In [5]:
following=[]
for page in tweepy.Cursor(api.get_friends, screen_name=elon,count=200).pages(10):
    for user in page:
        name = f"{user.name} (@{user.screen_name})"
        following.append(name)

In [28]:
len(following)

151

Save the following in a file using the json library

In [32]:
with open("following_raw","w") as fp:
    json.dump(following,fp)

Get the followers and save them in a file

After several tries, it was noticed that the limit rate was exceeded after 3000  followers were retrieved and also that the api needs 15 minutes to expires the timeout.

In [23]:
followers=[]
counter=0
for page in tweepy.Cursor(api.get_followers, screen_name=elon,count=200).pages(120):
    for user in page:
        name = f"{user.name} (@{user.screen_name})"
        followers.append(name)
        counter+=1
        if counter == 2999:
            counter=0
            time.sleep(15*60)   #sleep for 15 minutes
        if len(followers)>15000:
            break

TooManyRequests: 429 Too Many Requests
88 - Rate limit exceeded

In [26]:
len(followers)

33015

In [19]:
a=followers

In [22]:
b=followers

In [25]:
followers= a+b+followers

In [31]:
len(followers)

33015

Trying with different number of pages and time sleep, it was possible to get 33k followers

In [27]:
with open("followers_raw","w") as fp:
    json.dump(followers,fp)

We are going to use a webscraper to get elon's tweet. The tweets start from the beginning the 2018 because I think elon's notoriety has been increasing in the last 4 years.

The data extracted will contain the text, the number of likes, the number of retweets, the number of replies and the user mentions

In [3]:
tweets=[]
query = "(from:elonmusk) until:2022-12-11 since:2018-01-01"


start = time.time()
for tw in sntwitter.TwitterSearchScraper(query).get_items():
    tweets.append([tw.date,tw.content,tw.likeCount,tw.retweetCount,tw.replyCount, tw.mentionedUsers])
end = time.time()
print(end - start)

385.06362438201904

The data will be stored in dataframe and exported in a csv file using pandas

In [4]:
col = ["Date", "Tweet", "Likes","Retweet","Reply","Mention"]
df=pd.DataFrame(tweets,columns = col )
df

,Date,Tweet,Likes,Retweet,Reply,Mention
0,2022-12-10 23:22:58+00:00,@Twitter And many other features to come!,24783,1680,2583,[https://twitter.com/Twitter]
1,2022-12-10 20:01:11+00:00,https://t.co/80DdvpsNjM,647964,67179,20023,None
2,2022-12-10 19:56:59+00:00,Twitter is both a social media company and a c...,692416,95127,35890,None
3,2022-12-10 19:29:34+00:00,@elizableu Looks like Yoel is arguing in favor...,61853,15325,6071,[https://twitter.com/elizableu]
4,2022-12-10 19:21:31+00:00,@elizableu This explains a lot,91369,6914,1628,[https://twitter.com/elizableu]
...,...,...,...,...,...,...
15630,2018-01-07 03:00:48+00:00,@mhmtkcn Near 405,1150,28,47,[https://twitter.com/mhmtkcn]
15631,2018-01-05 00:30:15+00:00,https://t.co/3k71xzDIP1,26022,3489,609,None
15632,2018-01-05 00:30:00+00:00,Falcon Heavy goes vertical https://t.co/uG1k0W...,80594,13898,1974,None
15633,2018-01-03 08:22:31+00:00,Using a neural net to detect rain using camera...,16442,2169,655,None
15634,2018-01-03 05:38:16+00:00,Come work at the biggest &amp; most advanced f...,50036,6742,3028,None

In [ ]:
df.to_csv('elon.csv')

To handle task E of the assignment, the tweets of @dr_jpe have been collected

In [8]:
jpe_tweets=[]
query = "(from:dr_jpe) until:2022-12-11 since:2022-01-01"

for tw in sntwitter.TwitterSearchScraper(query).get_items():
    jpe_tweets.append([tw.date,tw.content,tw.likeCount,tw.retweetCount,tw.replyCount, tw.mentionedUsers])

In [9]:
col = ["Date", "Tweet", "Likes","Retweet","Reply","Mention"]
df_jpe=pd.DataFrame(jpe_tweets,columns = col )
df_jpe['Mention']=df_jpe['Mention'].fillna('No mention')
df_jpe

,Date,Tweet,Likes,Retweet,Reply,Mention
0,2022-12-10 08:07:07+00:00,"Our book chapter ""#ML for Metabolomic Pathway ...",8,0,0,"[https://twitter.com/UMmalta, https://twitter...."
1,2022-12-07 11:23:12+00:00,Christmas would not be the same without the #A...,2,1,0,No mention
2,2022-12-06 12:51:24+00:00,"@dwejjaq_enormi if you have to explain it, it'...",0,0,0,[https://twitter.com/dwejjaq_enormi]
3,2022-11-23 20:25:15+00:00,Come at @UMmalta to work on some #Bioinformati...,3,2,0,[https://twitter.com/UMmalta]
4,2022-11-18 12:44:41+00:00,I would say I am at least at lvl5\nhttps://t.c...,0,0,0,No mention
5,2022-11-15 10:36:09+00:00,#CPS3235 Assignment. @elonmusk is king.,1,0,1,[https://twitter.com/elonmusk]
6,2022-11-15 08:36:30+00:00,These are *read* emails. @airmalta why do you...,2,0,3,[https://twitter.com/AirMalta]
7,2022-11-15 04:57:06+00:00,@TheMarvel91 @Campanelli11 Ma anche un banalis...,0,0,0,"[https://twitter.com/TheMarvel91, https://twit..."
8,2022-10-14 19:37:26+00:00,@drmenguin I'm always game to some \LaTeX fun 😂,3,0,0,[https://twitter.com/drmenguin]
9,2022-10-14 11:04:06+00:00,Great to see @danvlla with his few-shot #Machi...,6,2,1,"[https://twitter.com/danvlla, https://twitter...."
10,2022-10-11 09:39:59+00:00,This morning's brew. Thanks @OPIGlets https:/...,11,0,2,[https://twitter.com/OPIGlets]
11,2022-09-12 14:28:18+00:00,New @UMmalta #LaTeX dissertation/thesis templa...,0,0,0,[https://twitter.com/UMmalta]
12,2022-08-18 13:51:14+00:00,"@NicholasMamo Fool Me Once, Shame on You; Fool...",0,0,0,[https://twitter.com/NicholasMamo]
13,2022-08-18 13:48:58+00:00,@NicholasMamo How can you complain? You sold t...,0,0,2,[https://twitter.com/NicholasMamo]
14,2022-08-16 13:59:30+00:00,@AcademicChatter I get asked this so often I a...,0,0,0,[https://twitter.com/AcademicChatter]
15,2022-08-15 14:47:38+00:00,@TheMarvel91 And he'd score more goals in a fo...,0,0,0,[https://twitter.com/TheMarvel91]
16,2022-08-10 10:02:06+00:00,Some of our doctoral research featured in Thin...,6,3,0,"[https://twitter.com/THINKUMtweets, https://tw..."
17,2022-08-09 13:10:14+00:00,@luca_desando @ilgobbo2002 But they can only p...,1,0,0,[https://twitter.com/luca_desando]
18,2022-07-29 10:36:35+00:00,Day 10 of the Data Science Summer School #DSSS...,3,0,1,[https://twitter.com/UMmalta]
19,2022-06-13 12:52:47+00:00,@realtalkjess I'd like to send a card as well ...,0,0,0,[https://twitter.com/realtalkjess]
20,2022-06-10 13:33:43+00:00,@It_Tre @FBiasin calunnia,0,0,0,"[https://twitter.com/It_Tre, https://twitter.c..."
21,2022-06-09 11:23:15+00:00,My Precioussss https://t.co/BLz0PuxHFO,16,0,0,No mention
22,2022-06-08 10:09:24+00:00,@remotesweden I used to have a recording for i...,0,0,0,[https://twitter.com/remotesweden]
23,2022-05-20 14:15:24+00:00,Some days are better than others ... https://t...,12,0,1,No mention
24,2022-05-16 21:32:22+00:00,"Ma come si fa a fischiare @andagn, ci ha fatto...",0,0,0,[https://twitter.com/andagn]
25,2022-05-14 07:00:09+00:00,@markussitzmann @TJCalculator @dr_greg_landrum...,0,0,0,"[https://twitter.com/markussitzmann, https://t..."
26,2022-05-06 10:38:36+00:00,@markcamilleri5 Fixed it for you: You're 😀,1,0,0,[https://twitter.com/markcamilleri5]
27,2022-04-27 20:35:01+00:00,@TheMarvel91 La Juve si e scansata un paio di ...,0,0,0,[https://twitter.com/TheMarvel91]
28,2022-04-26 13:22:22+00:00,Quite chuffed to see our #MScBioinformatics st...,4,0,0,"[https://twitter.com/UMmalta, https://twitter...."
29,2022-03-30 09:54:15+00:00,"""The counter-intuitive rise of #Python in #Sci...",1,0,0,No mention
30,2022-03-22 08:33:26+00:00,"@TheMarvel91 Nistu ma naqblux ta, il-hajja gha...",0,0,1,[https://twitter.com/TheMarvel91]
31,2022-03-22 08:30:35+00:00,@TheMarvel91 That is why I love football. Two...,0,0,0,[https://twitter.com/TheMarvel91]
32,2022-03-22 08:27:56+00:00,"@TheMarvel91 Goals this season: Udinese (x2), ...",0,0,1,[https://twitter.com/TheMarvel91]
33,2022-03-21 15:01:37+00:00,@TheMarvel91 U ejja Marco. Fl-ahhar tlett sea...,3,0,2,[https://twitter.com/TheMarvel91]
34,2022-03-10 21:54:08+00:00,@pisto_gol Ma parla di lei @It_Tre ?,0,0,0,"[https://twitter.com/pisto_gol, https://twitte..."
35,2022-03-03 11:51:34+00:00,@TheMarvel91 lil dan rajtu? Ezatt. https://t....,0,0,1,[https://twitter.com/TheMarvel91]
36,2022-03-02 21:09:28+00:00,@TheMarvel91 @piersmorgan Don't get me wrong. ...,0,0,0,"[https://twitter.com/TheMarvel91, https://twit..."
37,2022-03-02 21:04:26+00:00,@TheMarvel91 @piersmorgan Chelsea have £2B loa...,0,0,1,"[https://twitter.com/TheMarvel91, https://twit..."
38,2022-03-02 20:57:36+00:00,@TheMarvel91 @piersmorgan That is not what I i...,0,0,1,"[https://twitter.com/TheMarvel91, https://twit..."
39,2022-03-02 20:50:23+00:00,@TheMarvel91 @piersmorgan That talk is cheap. ...,0,0,1,"[https://twitter.com/TheMarvel91, https://twit..."
40,2022-03-02 20:41:50+00:00,"@TheMarvel91 @piersmorgan ""net proceeds"" were ...",0,1,2,"[https://twitter.com/TheMarvel91, https://twit..."
41,2022-02-16 14:58:17+00:00,"""Open office will not print on Tuesdays"" http...",0,0,0,No mention
42,2022-01-29 16:44:44+00:00,@TheMarvel91 Aħjar minn @aaronramsey,0,0,0,"[https://twitter.com/TheMarvel91, https://twit..."
43,2022-01-24 14:53:24+00:00,"Project #DisCO, finding novel #COVID19 inhibit...",1,0,0,"[https://twitter.com/TheTimesofMalta, https://..."
44,2022-01-21 16:11:54+00:00,Proud to be part of this team! #bioinformatics...,7,1,1,No mention
45,2022-01-18 12:02:10+00:00,Are you interested in a #bioinformatics (#mult...,2,2,0,[https://twitter.com/UMmalta]
46,2022-01-17 14:31:13+00:00,@curlyqubit @QuSysTCD @quantumwizard @edukazzj...,1,0,0,"[https://twitter.com/curlyqubit, https://twitt..."
47,2022-01-11 12:40:17+00:00,Science #visualization trends of 2021. Someth...,3,0,0,[https://twitter.com/helenajambor]

In [10]:
df_jpe.to_csv('jpe.csv')